site_name: pyMMF Documentation
site_url: https://wavefrontshaping.github.io/pyMMF/
nav:
  - Home: index.md
  - API Reference: api.md
  - Example 1: GRIN.ipynb
  - Example 2: Square_fiber.ipynb
  - Example 3: Benchmark_SI.ipynb

theme:
  name: material
  features:
    - navigation.footer
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.path
    - toc.integrate
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
      primary: teal
      accent: purple
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
      primary: teal
      accent: lime

plugins:
  - mkdocs-jupyter:
      include: ["*.ipynb"]
      ignore_h1_titles: True
      include_source: True
      remove_tag_config:
        remove_all_outputs_tags:
          - hide_output
  - social
  - search
  - mkdocstrings:
      handlers:
        python:
          paths:
            - ../
          options:
            show_source: false
      default_handler: python

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/wavefrontshaping
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/WFShaping

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

copyright: |
  &copy; 2024 <a href="https://github.com/wavefrontshaping"  target="_blank" rel="noopener">Sebastien M. Popoff</a>
