name: Tests

# Trigger the workflow on pushes and pull requests to the 'master' branch
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

# Define the jobs
jobs:
  test:
    # Run the job on the latest Ubuntu environment
    runs-on: ubuntu-latest

    # Set up Python and install dependencies
    steps:
      # Check out the code from the repository
      - name: Check out code
        uses: actions/checkout@v3

      # Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x" # Specify the version you want to use (e.g., 3.8, 3.9)

      # Install dependencies from requirements.txt or pyproject.toml
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Run the tests using pytest
      - name: Run pytest
        run: |
          pip install pytest  # Install pytest if not already in requirements
          pytest ./test  # Specify the folder where the tests are located

      # Optionally, upload test results if you want to see them in the Actions tab
      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: ./test-results.xml
