name: Python Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Use the latest version of actions
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x" # Specify the version you want to use (e.g., 3.8, 3.9)

      # Install dependencies from requirements.txt or pyproject.toml
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Run the tests using pytest
      - name: Run pytest
        run: |
          pip install pytest  # Install pytest if not already in requirements
          pytest ./test --junitxml=test-results.xml  # Generate test results as XML

      # Upload test results
      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: test-results.xml # Upload the test results XML file
